version: '2'

networks:
    bibbox-default-network:
      external: true

services:

  §§INSTANCE-dbninja:
    image: bibbox/dbninja
    container_name:  §§INSTANCE-dbninja
    restart: unless-stopped
    networks:
      - bibbox-default-network
    ports:
      - "§§PORT:80"
