version: '2'
services:

  §§INSTANCE-dbninja:
    image: bibbox/dbninja
    container_name:  §§INSTANCE-dbninja
    ports:
      - "§§PORT:80"

networks:
    default:
      external:
        name: bibbox-default-network

